## Loading data into Pandas

In [1]:
import pandas as pd

In [2]:
from google.colab import files
files.upload()

Saving M6_Pandas_Groupby_example_Data.csv to M6_Pandas_Groupby_example_Data.csv

{'M6_Pandas_Groupby_example_Data.csv': b'Name,Dept,Budget\r\nJohn,A,100\r\nSteve,B,200\r\nKathy,B,300\r\nCindi,A,500\r\nLarry,A,50\r\nGavin,A,550'}

In [3]:
df = pd.read_csv('M6_Pandas_Groupby_example_Data.csv')
df.head(6)

    Name Dept  Budget
0   John    A     100
1  Steve    B     200
2  Kathy    B     300
3  Cindi    A     500
4  Larry    A      50
5  Gavin    A     550

In [4]:
df.groupby('Dept').count()['Budget']

Dept
A    4
B    2
Name: Budget, dtype: int64

In [9]:
df.groupby('Dept').sum()['Budget']

Dept
A    1200
B     500
Name: Budget, dtype: int64

In [11]:
from numpy import int64
# Convert Budget to numeric; invalid values become NaN.
df['Budget'] = pd.to_numeric(df['Budget'], errors='coerce').astype(float)

# Group rows by department and calculate the average Budget for each department.
df.groupby('Dept')['Budget'].mean()

Dept
A    300.0
B    250.0
Name: Budget, dtype: float64