# HW6 Pandas Answer Key

Runnable instructor answer key notebook.

In [1]:
import pandas as pd

temps = {'Mon': [68, 89], 'Tue': [71, 93], 'Wed': [66, 82], 'Thu': [75, 97], 'Fri': [62, 79]}

Problem 1.Convert the Python dictionary ‘temps’ into the Python DataFrame named ‘temperatures’ with ‘Low’ and ‘High’ as the indices, then display the DataFrame.

In [2]:
temperatures = pd.DataFrame(temps, index=['Low', 'High'])
temperatures

      Mon  Tue  Wed  Thu  Fri
Low    68   71   66   75   62
High   89   93   82   97   79

Problem 2. Use the column names to select only the columns for ‘Mon’ through ‘Wed’.

In [3]:
temperatures.loc[:, 'Mon':'Wed']

      Mon  Tue  Wed
Low    68   71   66
High   89   93   82

Problem 3. Use the row index ‘Low’ to select only the low temperatures for each day.

In [4]:
temperatures.loc['Low']

Mon    68
Tue    71
Wed    66
Thu    75
Fri    62
Name: Low, dtype: int64

Problem 4. Set the floating-point precision to 2, then calculate the average temperature for each day.

In [5]:
pd.set_option('display.precision', 2)
temperatures.mean(axis=0)

Mon    78.5
Tue    82.0
Wed    74.0
Thu    86.0
Fri    70.5
dtype: float64

Problem 5. Calculate the average low and high temperatures.

In [6]:
temperatures.mean(axis=1)

Low     68.4
High    88.0
dtype: float64