# HW7 Movies Pandas Answer Key

### Answer key notebook. Run cells from top to bottom.
### There are 10 problems in this homework assignment.  Write a program in Python to solve these problems.  Use the ‘Pandas’ package to write your Python code. Use the data file (top_movies_by_title.csv) for all problems of this assignment.  This file contains information about 200 Hollywood movies.  This file is uploaded on Canvas available for download adjacent to the homework assignment#7.
### The first few rows of this file are displayed in the following figure

### The ‘Gross (Adjusted)’ amount is the inflation adjusted gross amount.  For example, ‘101 Dalmatians’ movie did $144 Million in 1961, it is equivalent to $869 Million in today’s dollars.

### Problem 1. Read the ‘top_movies_by_title.csv’ file into a Pandas’ data frame and name it ‘table1’.

The notebook uses the included `top_movies_by_title.csv` dataset.

In [1]:
from google.colab import files
f = files.upload()

Saving M7_top_movies_by_title.csv to M7_top_movies_by_title.csv

In [2]:
import pandas as pd

table1 = pd.read_csv("M7_top_movies_by_title.csv")
table1.head()

                   Title        Studio      Gross  Gross (Adjusted)  Year
0         101 Dalmatians        Disney  144880014         869280100  1961
1  2001: A Space Odyssey           MGM   56954992         377027700  1968
2                 9 to 5           Fox  103290500         334062200  1980
3  A Star Is Born (1976)  Warner Bros.   80000000         326760600  1976
4          Air Force One          Sony  172956409         327752300  1997

## Problem 2. Select ‘Title’ and ‘Year’ of the ‘table1’, into another table and name is ‘table2’.

In [3]:
table2 = table1[["Title", "Year"]]
table2

                       Title  Year
0             101 Dalmatians  1961
1      2001: A Space Odyssey  1968
2                     9 to 5  1980
3      A Star Is Born (1976)  1976
4              Air Force One  1997
..                       ...   ...
195                       Up  2009
196          West Side Story  1961
197          What's Up, Doc?  1972
198  Who Framed Roger Rabbit  1988
199       Young Frankenstein  1974

[200 rows x 2 columns]

## Problem 3. Select only the movies from ‘table1’ where the gross revenues generated by the movie exceeds 100 million.

In [4]:
gross_over_100m = table1[table1["Gross"] > 100000000]
gross_over_100m

,Title,Studio,Gross,Gross (Adjusted),Year
0,101 Dalmatians,Disney,144880014,869280100,1961
2,9 to 5,Fox,103290500,334062200,1980
4,Air Force One,Sony,172956409,327752300,1997
5,Airport,Universal,100489151,575168200,1970
6,Aladdin,Buena Vista (Disney),217350219,456248400,1992
...,...,...,...,...,...
192,Transformers: Dark of the Moon,Paramount/Dreamworks,352390543,385069700,2011
193,Transformers: Revenge of the Fallen,Paramount/Dreamworks,402111870,468938100,2009
194,Twister,Warner Bros.,241721524,475786700,1996
195,Up,Buena Vista (Disney),293004164,341681900,2009
198,Who Framed Roger Rabbit,Buena Vista (Disney),156452370,331176600,1988

In [5]:
gross_over_100m.sort_values("Gross", ascending=True)

,Title,Studio,Gross,Gross (Adjusted),Year
5,Airport,Universal,100489151,575168200,1970
138,Stir Crazy,Columbia,101300000,327624500,1980
18,Bambi,RKO,102247150,554298300,1942
87,Mary Poppins,Disney,102272727,680181800,1964
28,Butch Cassidy and the Sundance Kid,Fox,102308889,613853300,1969
...,...,...,...,...,...
86,Marvel's The Avengers,Buena Vista (Disney),623357910,668866600,2012
78,Jurassic World,Universal,652270625,687728000,2015
185,Titanic,Paramount,658672302,1178627900,1997
15,Avatar,Fox,760507625,846120800,2009
137,Star Wars: The Force Awakens,Buena Vista (Disney),906723418,906723400,2015

## Problem 4.  Select only the movies from ‘table1’ where the gross revenues generated by the movie is between 100 and 200 million. Sort the output data frame by 'Gross' revenues in descending order. Display only the top 10 entries.

In [6]:
gross_100_to_200m_top10 = (
    table1[(table1["Gross"] >= 100_000_000) & (table1["Gross"] <= 200_000_000)]
    .sort_values("Gross", ascending=False)
    .head(10)
)
gross_100_to_200m_top10

,Title,Studio,Gross,Gross (Adjusted),Year
51,Gone with the Wind,MGM,198676459,1757788200,1939
69,Indiana Jones and the Last Crusade,Paramount,197171806,429923500,1989
188,Toy Story,Buena Vista (Disney),191796233,381654400,1995
52,Grease,Paramount,188755690,669632000,1978
129,Snow White and the Seven Dwarfs,Disney,184925486,948300000,1937
35,Dances with Wolves,Orion,184208848,380183900,1990
20,Batman Forever,Warner Bros.,184031112,368062200,1995
154,The Fugitive,Warner Bros.,183875760,386256600,1993
83,Liar Liar,Universal,181410615,343850200,1997
91,Mission: Impossible,Paramount,180981856,356231300,1996

## Problem 5. Select movies where the word ‘the’ appears in the title of the movie.  Show the first 10 movies.

In [7]:
table1[table1['Title'].str.contains('the', na=False)].head(10)

,Title,Studio,Gross,Gross (Adjusted),Year
13,Around the World in 80 Days,UA,42000000,562153800,1956
17,Back to the Future,Universal,210609762,513740700,1985
22,Beauty and the Beast,Buena Vista (Disney),218967620,394664300,1991
28,Butch Cassidy and the Sundance Kid,Fox,102308889,613853300,1969
33,Close Encounters of the Third Kind,Columbia,132088635,483507200,1977
38,Duel in the Sun,Selz.,20408163,443877500,1946
51,Gone with the Wind,MGM,198676459,1757788200,1939
54,Guardians of the Galaxy,Buena Vista (Disney),333176600,358244800,2014
56,Harry Potter and the Chamber of Secrets,Warner Bros.,261988482,390768100,2002
57,Harry Potter and the Deathly Hallows Part 2,Warner Bros.,381011219,417512200,2011

In [8]:
movies_with_the = table1[table1["Title"].str.contains("the", case=False, na=False)]
movies_with_the.head(10)

,Title,Studio,Gross,Gross (Adjusted),Year
13,Around the World in 80 Days,UA,42000000,562153800,1956
14,Austin Powers: The Spy Who Shagged Me,New Line,206040086,352863900,1999
17,Back to the Future,Universal,210609762,513740700,1985
22,Beauty and the Beast,Buena Vista (Disney),218967620,394664300,1991
28,Butch Cassidy and the Sundance Kid,Fox,102308889,613853300,1969
33,Close Encounters of the Third Kind,Columbia,132088635,483507200,1977
38,Duel in the Sun,Selz.,20408163,443877500,1946
39,E.T.: The Extra-Terrestrial,Universal,435110554,1234132700,1982
51,Gone with the Wind,MGM,198676459,1757788200,1939
54,Guardians of the Galaxy,Buena Vista (Disney),333176600,358244800,2014

## Problem 6. Sort the movies in ‘table1’ in descending order (highest value first) by their ‘Gross’ revenues.  Select top 3 movies made the most amount of money based on ‘Gross’ column? Select top 3 movies made the most amount of money based on ‘Gross (Adjusted)’ column?

In [9]:
top3_gross = table1.sort_values("Gross", ascending=False).head(3)
top3_adjusted = table1.sort_values("Gross (Adjusted)", ascending=False).head(3)

print("Top 3 by Gross")
display(top3_gross)

print("Top 3 by Gross (Adjusted)")
display(top3_adjusted)

Top 3 by Gross

,Title,Studio,Gross,Gross (Adjusted),Year
137,Star Wars: The Force Awakens,Buena Vista (Disney),906723418,906723400,2015
15,Avatar,Fox,760507625,846120800,2009
185,Titanic,Paramount,658672302,1178627900,1997

Top 3 by Gross (Adjusted)

                  Title Studio      Gross  Gross (Adjusted)  Year
51   Gone with the Wind    MGM  198676459        1757788200  1939
133           Star Wars    Fox  460998007        1549640500  1977
176  The Sound of Music    Fox  158671368        1239013800  1965

## Problem 7. Count the number of movies from each studio.  How many movies made by ‘Columbia’ and ‘Fox’ studios?

In [10]:
studio_counts = table1["Studio"].value_counts()
display(studio_counts)

print("Columbia:", studio_counts.get("Columbia", 0))
print("Fox:", studio_counts.get("Fox", 0))

Studio
Warner Bros.               29
Buena Vista (Disney)       29
Fox                        26
Paramount                  25
Universal                  22
Disney                     11
Columbia                   10
MGM                         7
Sony                        6
UA                          6
New Line                    5
Paramount/Dreamworks        4
Dreamworks                  3
Lionsgate                   3
RKO                         3
TriS                        2
Sum.                        2
IFC                         1
Orion                       1
Selz.                       1
AVCO                        1
MPC                         1
Warner Bros. (New Line)     1
NM                          1
Name: count, dtype: int64

Columbia: 10
Fox: 26

## Problem 8. Which is the highest grossing movie from ‘Columbia’ studio?

In [11]:
highest_columbia = table1[table1["Studio"] == "Columbia"].sort_values("Gross", ascending=False).head(1)
highest_columbia

           Title    Studio      Gross  Gross (Adjusted)  Year
49  Ghostbusters  Columbia  242212467         619211400  1984

In [12]:
table1[table1["Studio"] == "Columbia"].nlargest(1, "Gross")

           Title    Studio      Gross  Gross (Adjusted)  Year
49  Ghostbusters  Columbia  242212467         619211400  1984

In [13]:
table1[table1["Studio"] == "Columbia"] \
    .sort_values("Gross", ascending=False) \
    .head(1)

           Title    Studio      Gross  Gross (Adjusted)  Year
49  Ghostbusters  Columbia  242212467         619211400  1984

## Problem 9.  Compute the ratio between ‘Gross (Adjusted)’ and ‘Gross’ for all movies.  Next sort the table by the ratio in descending order.  Display the top 10 ratios.

In [14]:
table1["Ratio"] = table1["Gross (Adjusted)"] / table1["Gross"]
top10_ratios = table1.sort_values("Ratio", ascending=False).head(10)
top10_ratios

,Title,Studio,Gross,Gross (Adjusted),Year,Ratio
153,The Four Horsemen of the Apocalypse,MPC,9183673,399489800,1921,43.500003
143,The Bells of St. Mary's,RKO,21333333,545882400,1945,25.588238
121,Sergeant York,Warner Bros.,16361885,418671800,1941,25.588238
38,Duel in the Sun,Selz.,20408163,443877500,1946,21.749998
144,The Best Years of Our Lives,RKO,23650000,478500000,1946,20.232558
65,House of Wax,Warner Bros.,23750000,439627700,1953,18.510640
146,The Caine Mutiny,Columbia,21750000,386173500,1954,17.755103
145,The Bridge on the River Kwai,Columbia,27200000,473280000,1957,17.400000
178,The Ten Commandments,Paramount,65500000,1139700000,1956,17.400000
173,The Robe,Fox,36000000,569454500,1953,15.818181

## Problem 10. Group all the movies by the year in which they were released.  In which year has the maximum number of movies released?

In [15]:
movies_by_year = table1.groupby("Year").size().sort_values(ascending=False)
display(movies_by_year)

print("Year with maximum number of movies:", movies_by_year.idxmax())
print("Number of movies:", movies_by_year.max())

Year
2004    6
2002    6
2009    6
2015    6
2012    5
       ..
1952    1
1955    1
1945    1
1957    1
1962    1
Length: 70, dtype: int64

Year with maximum number of movies: 2004
Number of movies: 6